modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Difficulty%20Lock"
logoFile="icon.png"

[[mods]]
modId="difficultylock"
version="3.0"
displayName="Difficulty Lock"
displayURL="https://curseforge.com/minecraft/mc-mods/difficulty-lock"
authors="Rick South"
description='''Sets the difficulty to peaceful/easy/normal/hard in any (new) world, optionally locked.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.difficultylock]]
    modId="collective"
    mandatory=true
    versionRange="[6.21,)"
    ordering="NONE"
    side="BOTH"