modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Difficulty%20Lock"
logoFile="icon.png"

[[mods]]
modId="difficultylock"
version="3.2"
displayName="Difficulty Lock"
displayURL="https://serilum.com/mod/difficulty-lock"
authors="Rick South"
description='''Sets the difficulty to peaceful/easy/normal/hard in any (new) world, optionally locked.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.difficultylock]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.difficultylock]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"